'use strict'
const Benchmark = require('@spazmodius/hrbench')
const uuid = require('uuid')
const fastguid = require('./fastGuid')

new Benchmark()
	.test('uuid', uuid)
	.test('uuid.v4', uuid.v4)
	.test(fastguid)
	.test('fastguid.D', fastguid.D)
	.test('fastguid.N', fastguid.N)
	.test('fastguid.B', fastguid.B)
	.run()
	.then(Benchmark.summarize)
	.then(console.log)
	.catch(console.err)
